### ISSUE TITLE
Account name that contains illegal characters will be parsed into two rows

### ISSUE THREAD

**Issue by think-in-universe** [zavodil/near-multisender#1]
### Description

Fill in `a15108499262@.near,3` into the textarea of multi-sender. It will be parsed into two lines, but we're lucky those two accounts are both invalid, and they are both removed when clicking **Verify Accounts**

![image](https://user-images.githubusercontent.com/46699230/118267123-23c10300-b4ee-11eb-80f6-f2cdef02f89b.png)

What if the input is `a15108499262@abc.near,3`, the line will also be parsed into two rows, and in this case, the 2nd account 
`abc.near` is valid. We may transfer to a wrong account if we we don't go through the parsed account names carefully.

![image](https://user-images.githubusercontent.com/46699230/118267511-c4afbe00-b4ee-11eb-84e2-93edd7d85054.png)

**Comment by zavodil** [comment]
Thank you! Regex updated #https://github.com/zavodil/near-multisender/commit/3c68451560e611fdcb8e1bc38bae17b2c460539e

could you check now please?
