### ISSUE TITLE
Consider decreasing the registered balance before transfering

### ISSUE THREAD

**Issue by swfsql** [zavodil/near-multisender#2]
The current behavior, when sending from the tracked/registered balance, is to make the transfer transaction and then on a callback check if the transfer was successful and then decrease the registered balance.

I think this could be problematic for an account that uses multiple keys and makes simultaneous calls to that transfer function, as they all could occur in the same block (and in the same batch of transactions) before any of their callbacks gets executed.

To prevent this, I think it's possible to decrement in the same transaction of the transfer itself, and on the callback, check for failure cases, and in case of failures, actually re-increment/restore the registered balance.

**Comment by zavodil** [comment]
Thank you! Contract updated in https://github.com/zavodil/near-multisender/commit/fba58261ee30c222cf60f7213a66657061e6882e
